name: Copy Code by Commit ID

on:
  workflow_dispatch:
    inputs:
      commit_id:
        required: true
        description: 'Commit ID to use for copying'

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: Use Entered Commit ID
      id: commit_id_input
      run: |
        COMMIT_ID="${{ github.event.inputs.commit_id }}"
        echo "Using Commit ID: $COMMIT_ID"

    - name: Checkout code at Commit ID
      run: |
        COMMIT_ID="${{ steps.commit_id_input.outputs.COMMIT_ID }}"
        git clone --depth 1 --branch $COMMIT_ID https://github.com/${{ github.repository }} .
        rm -rf .git  

    - name: Copy code to GCS bucket
      run: |
        gsutil -m cp -r . gs://testmmf/$COMMIT_ID/
