name: Copy Code by Commit ID

on:
  workflow_dispatch:
    inputs:
      commit_id:
        required: true
        description: 'Commit ID to use for copying'

jobs:
  copy:
    runs-on: ubuntu-latest
    permissions:
       contents: 'read'
       id-token: 'write'

    steps:
    - id: auth
      name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        token_format: access_token
        workload_identity_provider: ${{ secrets.WIP }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
        access_token_lifetime: 300s
        project_id: "dev-matchmyflight"
        
    - name: Use Entered Commit ID
      id: commit_id_input
      run: |
        COMMIT_ID="${{ github.event.inputs.commit_id }}"
        echo "Using Commit ID: $COMMIT_ID"

    - name: Clone repository and checkout Commit ID
      run: |
        COMMIT_ID="${{ steps.commit_id_input.outputs.COMMIT_ID }}"
        git clone --depth 1 https://github.com/${{ github.repository }} /tmp/repo
        git --git-dir=/tmp/repo/.git --work-tree=/tmp/repo checkout $COMMIT_ID

    - name: Create zip archive
      run: |
        COMMIT_ID="${{ steps.commit_id_input.outputs.COMMIT_ID }}"
        zip -r code.zip -j /tmp/repo/*

    - name: Unzip code
      run: |
        unzip -q code.zip -d /tmp/unzipped
        mv /tmp/unzipped/* /tmp/repo/
        rm -rf /tmp/unzipped

    - name: Authorize gsutil
      uses: google-github-actions/setup-gcloud@v1
        
    - name: Copy code to GCS bucket
      run: |
        gsutil -m cp -r /tmp/repo/* gs://testmmf/$COMMIT_ID/
