name: 'Automated Deployment'

on:
  push:
    branches:
      - develop

env:
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: auth
      name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        token_format: access_token
        workload_identity_provider: ${{ secrets.WIP }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
        access_token_lifetime: 300s
        project_id: "{YOUR-PROJECT-ID}"
    
    - name: Authorize gsutil
      uses: google-github-actions/setup-gcloud@v1
        
    - name: Setup credentials to access private repositories
      run: | 
        git config --global url.https://${{ secrets.MY_PAT }}@github.com/.insteadOf https://github.com/
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.16.0"

    - name: Installing all dependencies of the Application
      run: |
        flutter pub get

    - name: Building apk of the application
      run: |
        flutter build apk --release

    - name: Copying the apk to Cloud Storage
      run: |
        gsutil cp build/app/outputs/flutter-apk/app-release.apk gs://{YOUR-BUCKET-NAME}/

    - name: Building app bundle for playstore
      run: |
         flutter build appbundle

    - name: |
      run: |
        gsutil cp build/app/outputs/bundle/release/app-release.aab gs://{YOUR-BUCKET-NAME}/